//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIENXE()
        {
            this.CHITIETBAOTRIs = new HashSet<CHITIETBAOTRI>();
            this.HOADONTHUEXEs = new HashSet<HOADONTHUEXE>();
        }
    
        public string BIENXE1 { get; set; }
        public string MATT { get; set; }
        public Nullable<int> SOKM { get; set; }
        public string MAXE { get; set; }
        public string MAUSAC { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        public virtual TINHTRANG TINHTRANG { get; set; }
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOTRI> CHITIETBAOTRIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTHUEXE> HOADONTHUEXEs { get; set; }
    }
}
