//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETLICHCHAY
    {
        public string BIENXE { get; set; }
        public string MAHD { get; set; }
        public string MATAIXE { get; set; }
        public Nullable<bool> DAHOANTHANH { get; set; }
        public string NOIDON { get; set; }
        public string NOIDI { get; set; }
    
        public virtual TKTAIXE TKTAIXE { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE { get; set; }
    }
}
