//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHANHTOAN
    {
        public string MAPTT { get; set; }
        public string MANV { get; set; }
        public string TONGSOTIEN { get; set; }
        public string GHICHU { get; set; }
        public string MAHD { get; set; }
        public Nullable<bool> DATHANHTOAN { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
    
        public virtual HOADONTHUEXE HOADONTHUEXE { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
