//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDENBU
    {
        public string MAPDB { get; set; }
        public Nullable<System.DateTime> NGAYDENBU { get; set; }
        public Nullable<int> TONGGIATIEN { get; set; }
        public string NOIDUNG { get; set; }
        public string MANV { get; set; }
        public string MAHD { get; set; }
        public string MABH { get; set; }
        public string MAKH { get; set; }
    
        public virtual BAOHIEM BAOHIEM { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
