//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.BIENXEs = new HashSet<BIENXE>();
        }
    
        public string MAXE { get; set; }
        public string TENXE { get; set; }
        public string MAHANG { get; set; }
        public string MANL { get; set; }
        public string MASG { get; set; }
        public string NXS { get; set; }
        public Nullable<int> LUOTTHUE { get; set; }
        public Nullable<int> GIATHUE { get; set; }
        public Nullable<int> GIATAIXE { get; set; }
        public Nullable<int> GIATAIXEKH { get; set; }
        public string ANH { get; set; }
        public string MIEUTA { get; set; }
        public Nullable<bool> TUDONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENXE> BIENXEs { get; set; }
        public virtual HANGXE HANGXE { get; set; }
        public virtual NHIENLIEU NHIENLIEU { get; set; }
        public virtual SOGHE SOGHE { get; set; }
    }
}
