//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHIEM
    {
        public string MABH { get; set; }
        public string MAKH { get; set; }
        public Nullable<int> GIATRI { get; set; }
        public Nullable<System.DateTime> NGAYSUDUNG { get; set; }
        public Nullable<bool> DASUDUNG { get; set; }
        public Nullable<System.DateTime> NGAYCAP { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
