//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTHUEXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETTHUEXE()
        {
            this.CHITIETLICHCHAYs = new HashSet<CHITIETLICHCHAY>();
        }
    
        public string BIENXE { get; set; }
        public string MAHD { get; set; }
        public Nullable<bool> COTAIXE { get; set; }
        public Nullable<int> CHIPHI { get; set; }
        public Nullable<int> SONGAYTHUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLICHCHAY> CHITIETLICHCHAYs { get; set; }
        public virtual XE XE { get; set; }
    }
}
