//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIAOXE
    {
        public string MATAIXE { get; set; }
        public string MAHD { get; set; }
        public string MAKH { get; set; }
        public Nullable<bool> DAHOANTHANH { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public string NOIDON { get; set; }
    
        public virtual TKTAIXE TKTAIXE { get; set; }
        public virtual TKTAIXE TKTAIXE1 { get; set; }
        public virtual TKTAIXE TKTAIXE2 { get; set; }
        public virtual THUEXETULAI THUEXETULAI { get; set; }
        public virtual THUEXETULAI THUEXETULAI1 { get; set; }
        public virtual THUEXETULAI THUEXETULAI2 { get; set; }
    }
}
