//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTHUEXETAIXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETTHUEXETAIXE()
        {
            this.CHITIETLICHCHAYs = new HashSet<CHITIETLICHCHAY>();
            this.CHITIETLICHCHAYs1 = new HashSet<CHITIETLICHCHAY>();
            this.CHITIETLICHCHAYs2 = new HashSet<CHITIETLICHCHAY>();
        }
    
        public string BIENXE { get; set; }
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYCHAY { get; set; }
        public int CHIPHITHUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLICHCHAY> CHITIETLICHCHAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLICHCHAY> CHITIETLICHCHAYs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLICHCHAY> CHITIETLICHCHAYs2 { get; set; }
        public virtual XE XE { get; set; }
        public virtual XE XE1 { get; set; }
        public virtual XE XE2 { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE1 { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE2 { get; set; }
    }
}
