//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBAOTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUBAOTRI()
        {
            this.CHITIETBAOTRIs = new HashSet<CHITIETBAOTRI>();
        }
    
        public string MAPBT { get; set; }
        public string MANVBAIXE { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYBA0TRI { get; set; }
        public Nullable<int> TONGCHIPHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOTRI> CHITIETBAOTRIs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIENQLBAIXE NHANVIENQLBAIXE { get; set; }
    }
}
