//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUEXETULAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUEXETULAI()
        {
            this.CHITIETGIAOXEs = new HashSet<CHITIETGIAOXE>();
            this.CHITIETGIAOXEs1 = new HashSet<CHITIETGIAOXE>();
            this.CHITIETGIAOXEs2 = new HashSet<CHITIETGIAOXE>();
            this.PHIEUDENBUs = new HashSet<PHIEUDENBU>();
            this.PHIEUDENBUs1 = new HashSet<PHIEUDENBU>();
            this.PHIEUDENBUs2 = new HashSet<PHIEUDENBU>();
        }
    
        public string MAHD { get; set; }
        public string MAKH { get; set; }
        public string BIENXE { get; set; }
        public Nullable<System.DateTime> NGAYNHAN { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIAOXE> CHITIETGIAOXEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIAOXE> CHITIETGIAOXEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIAOXE> CHITIETGIAOXEs2 { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE1 { get; set; }
        public virtual HOADONTHUEXE HOADONTHUEXE2 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHACHHANG KHACHHANG1 { get; set; }
        public virtual KHACHHANG KHACHHANG2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDENBU> PHIEUDENBUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDENBU> PHIEUDENBUs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDENBU> PHIEUDENBUs2 { get; set; }
        public virtual XE XE { get; set; }
        public virtual XE XE1 { get; set; }
        public virtual XE XE2 { get; set; }
    }
}
