//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthuexe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHITIETBAOTRIs = new HashSet<CHITIETBAOTRI>();
            this.CHITIETTHUEXEs = new HashSet<CHITIETTHUEXE>();
        }
    
        public string BIENXE { get; set; }
        public string MAHANG { get; set; }
        public string MANL { get; set; }
        public string MASG { get; set; }
        public string TENXE { get; set; }
        public string NXS { get; set; }
        public int LUOTTHUE { get; set; }
        public int GIATHUE { get; set; }
        public int GIATAIXE { get; set; }
        public string DONVITINH { get; set; }
        public string MATT { get; set; }
        public Nullable<int> SOKM { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MAUSAC { get; set; }
        public string ANH { get; set; }
        public string MIEUTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOTRI> CHITIETBAOTRIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTHUEXE> CHITIETTHUEXEs { get; set; }
        public virtual HANGXE HANGXE { get; set; }
        public virtual NHIENLIEU NHIENLIEU { get; set; }
        public virtual SOGHE SOGHE { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
